<?php

$title = 'Add new record';
$this->headTitle($title);

?>
<h3><?=$this->escapeHtml($title);?></h3>
<?php

$form->setAttribute('action',$this->url('crud',['action'=>'add']));
echo $this->form()->openTag($form);
echo $this->formRow($form->get('title')); echo "<br/>";
echo $this->formRow($form->get('description')); echo "<br/>";
echo $this->formRow($form->get('category')); echo "<br/>";
echo $this->formRow($form->get('submit'));

