<?php

$title = 'Delete record';
$this->headTitle($title);

$url = $this->url('crud',['action'=>'delete','id'=>$id]);

?>
<h3><?=$this->escapeHtml($title);?></h3>
<form action="<?=$url;?>" method="POST">
<p>Are your sure?</p>
<div class="form-group">
    <input type="hidden" name='id' value='<?=$id?>' />
    <input type="submit" name="delete" value="Yes" class="btn btn-danger">
    <input type="submit" name="delete" value="No" class="btn btn-primary">
</div>
</form>

